import {createClient} from '@supabase/supabase-js';
import {createHmac,timingSafeEqual,randomBytes} from 'node:crypto';
import {cookies} from 'next/headers';
export const db=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const key=()=>{if(!process.env.SESSION_SECRET||process.env.SESSION_SECRET.length<32)throw Error('Configure SESSION_SECRET com pelo menos 32 caracteres');return process.env.SESSION_SECRET};
const sign=s=>createHmac('sha256',key()).update(s).digest('base64url');
export const makeToken=(role,id)=>{const payload=Buffer.from(JSON.stringify({role,id,exp:Date.now()+1000*60*60*12,nonce:randomBytes(8).toString('hex')})).toString('base64url');return payload+'.'+sign(payload)};
export async function identity(){const jar=await cookies();const token=jar.get('grelinho_session')?.value;if(!token)return null;const [payload,mac,...rest]=token.split('.');if(!payload||!mac||rest.length)return null;const expected=sign(payload);if(mac.length!==expected.length||!timingSafeEqual(Buffer.from(mac),Buffer.from(expected)))return null;try{const data=JSON.parse(Buffer.from(payload,'base64url').toString());return data.exp>Date.now()&&['admin','participant'].includes(data.role)?data:null}catch{return null}}
export const reply=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export const fail=(error,status=400)=>reply({error},status);
export async function expire(){const {error}=await db().rpc('expirar_rodadas_servidor');if(error)throw Error(error.message)}
export async function getState(who){const s=db();const {data:prizes,error:e1}=await s.from('premios').select('id,estado,vencedor_id');if(e1)throw Error(e1.message);const {data:dares,error:e2}=await s.from('desafios').select('id,bonus,utilizado');if(e2)throw Error(e2.message);const {data:rounds,error:e3}=await s.from('rodadas').select('id,participante_id,premio_id,desafio_id,estado,prazo_desafio').in('estado',['aguardando_desafio','em_andamento']);if(e3)throw Error(e3.message);const mine=who.role==='admin'?rounds[0]:rounds.find(r=>r.participante_id===who.id);let active=null;if(mine){active={id:mine.id,estado:mine.estado,prazo:mine.prazo_desafio,participante_id:mine.participante_id};const {data:p}=await s.from('premios').select('nome,imagem_url').eq('id',mine.premio_id).single();active.premio=p;if(mine.desafio_id){const {data:d}=await s.from('desafios').select('titulo,descricao,bonus').eq('id',mine.desafio_id).single();active.desafio=d;}}const {data:me}=who.role==='participant'?await s.from('participantes').select('nome').eq('id',who.id).single():{data:null};const {data:won}=who.role==='participant'?await s.from('premios').select('id').eq('vencedor_id',who.id).limit(1):{data:[]};return {role:who.role,nome:me?.nome||'Organizadora',active,won:!!won?.length,prizesAvailable:prizes.filter(p=>p.estado==='disponivel').length,daresAvailable:dares.filter(d=>!d.bonus&&!d.utilizado).length};}
